```{r}
library(forecast)
library(ggplot2)
library(tidyr)
```

# Types of noise 
## 1.1.1. White noise
Variable $w_t$ is a white noise if it meets only three conditions: 
- $E(w_t) = 0$,
- $Var(w_t) = \sigma^2$,
- $cov(w_t, w_s) = 0$.

Note it doesn't have to be normally distributed (then we call it "gaussian noise") - but in many cases it is. 

```{r, fig.width= 8, fig.height = 5}
set.seed(0)
white_noise = rnorm(200)
tsdisplay(white_noise, plot.type = "histogram", points = FALSE)
```

```{r}
mean(white_noise)
var(white_noise)
```

```{r}
set.seed(0) # for seed = 7 there is an accidental autocorrelation
white_noise2 = runif(200, min = -1, max = 1)
tsdisplay(white_noise2, plot.type = "histogram", points = FALSE)
```

```{r}
mean(white_noise2)
var(white_noise2) # 1/3 is a theoretical value
```

## AR(p) processes
The Autoregressive process is given by the equation

$$X_t = \sum^p_{i=1} \theta_i X_{t-i} + w_t.$$

```{r, fig.width = 16, fig.height = 5}
N <- 200
ar1_processes <- matrix(nrow = 7, ncol = N)
ar1_processes[1,] <- 1:N
ar1_processes[2,] <- arima.sim(model = list(ar = c(0.1)), n = N)
ar1_processes[3,] <- arima.sim(model = list(ar = c(0.5)), n = N)
ar1_processes[4,] <- arima.sim(model = list(ar = c(0.9)), n = N)
ar1_processes[5,] <- arima.sim(model = list(ar = c(-0.1)), n = N)
ar1_processes[6,] <- arima.sim(model = list(ar = c(-0.5)), n = N)
ar1_processes[7,] <- arima.sim(model = list(ar = c(-0.9)), n = N)

# Note: you can use arima.sim only to simulate a stationary process. To simulate non-stationary one,
# use Arima.

ar1_processes <- as.data.frame(t(ar1_processes)) 
colnames(ar1_processes) <- c(
  "time", "theta = 0.1", "theta = 0.5", "theta = 0.9", "theta = -0.1", "theta = -0.5", "theta = -0.9")

ar1_processes %>% pivot_longer(cols = 2:7) %>% 
  ggplot(aes(x = time, y = value, col = name)) +
  geom_line() + ggtitle("AR(1) processes with different coefficient (only stationary, i.e. |theta| < 1 allowed by arima.sim)")
```

